### PR TITLE
added example to oversample image data using LLE Smote.

### PR DESCRIPTION
**Pull request by sakethbachu**
@gykovacs I have added the example where I have demonstrated the usage of LLE-Smote on image data. Please review it and let me know if there are any changes to make :)

### CODE REVIEW

**Comment by sakethbachu** [comment]
@gykovacs I did not quite understand the build error :/

**Comment by gykovacs** [comment]
Great job! :) I look into the build error, might be some configurational issue.

**Comment by gykovacs** [comment]
Yes, it is, could you please edit the requirements.txt file to "numpy>=1.16.0,<1.19.0"?

**Comment by sakethbachu** [comment]
@gykovacs I have not added any requirements.txt file, ;(

**Comment by gykovacs** [comment]
No, that' not a problem. Seemingly, since the latest upgrade, numpy as upgraded and/or tensorflow changed its requirements to numpy < 1.19.0, so even though the tests passed by the time of the latest upgrade, now, installing the latest numpy does not work with tensorflow. So its not your fault :). Let me fix it in master.

**Comment by sakethbachu** [comment]
Thank you so much, I wish to contribute more in the future 💯

**Comment by gykovacs** [comment]
Thank you for the contribution! Great, any further contribution is very welcome! :)

**Pull request merged**
